In [1]:
import pandas as pd
df=pd.read_csv('primary_input.csv')
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
df

     A.Age  A.Gender  A.Education Level  A.Monthly Income  A.Marital Status  \
0       34         1                  2                 2                 0
1       36         0                  2                 3                 0
2       35         1                  2                 2                 0
3       40         1                  2                 2                 0
4       32         1                  2                 1                 0
5       30         0                  2                 1                 1
6       40         1                  2                 3                 0
7       38         1                  2                 2                 1
8       28         0                  2                 1                 0
9       31         0                  2                 2                 1
10      33         0                  2                 2                 1
11      33         0                  2                 2                 1
12      36         0                  2                 0                 1
13      28         1                  2                 1                 0
14      30         0                  2                 1                 0
15      27         0                  2                 1                 1
16      26         0                  2                 1                 1
17      32         1                  2                 2                 0
18      35         0                  2                 2                 1
19      26         1                  2                 1                 1
20      32         1                  2                 1                 0
21      33         1                  2                 2                 0
22      40         1                  1                 1                 0
23      32         0                  2                 1                 0
24      35         1                  1                 1                 0
25      42         1                  2                 1                 0
26      41         1                  2                 3                 0
27      36         0                  2                 2                 0
28      36         0                  2                 1                 0
29      49         1                  2                 2                 0
30      36         1                  2                 1                 0
31      47         1                  2                 2                 0
32      45         1                  2                 1                 0
33      34         1                  2                 2                 0
34      32         0                  2                 2                 0
35      32         1                  2                 2                 0
36      33         1                  2                 2                 1
37      35         0                  2                 2                 0
38      34         1                  2                 2                 0
39      32         1                  2                 0                 0
40      32         1                  2                 2                 0
41      28         0                  2                 1                 1
42      35         0                  2                 2                 0
43      33         1                  2                 2                 0
44      29         1                  2                 1                 1
45      32         0                  2                 1                 0
46      37         0                  2                 2                 0
47      28         1                  2                 2                 1
48      32         1                  2                 2                 0
49      34         0                  2                 2                 1
50      35         1                  2                 2                 0
51      33         1                  2                 1                 1
52      32         0                  2                 1                 0
53      48         0                  2                 2                 0
54      38         1                  2                 2                 0
55      35         1                  2                 2                 0
56      45         1                  2                 1                 0
57      31         0                  2                 1                 0
58      33         0                  2                 2                 0
59      34         1                  2                 2                 1
60      30         0                  2                 1                 0
61      28         1                  2                 1                 0
62      36         0                  2                 2                 0
63      36         0                  2                 2                 0
64      32         0                  2                 1                 0
65      41         1                  2                 1                 1
66      34         0                  2                 2                 0
67      32         1                  2                 2                 1
68      28         1                  2                 1                 0
69      32         1                  2                 2                 0
70      32         0                  2                 2                 1
71      27         1                  2                 1                 0
72      48         1                  2                 2                 0
73      32         1                  2                 1                 1
74      35         1                  2                 2                 0
75      35         1                  2                 2                 0
76      30         1                  2                 2                 0
77      32         1                  2                 2                 0
78      32         1                  2                 2                 0
79      34         1                  2                 2                 0
80      35         0                  2                 2                 0
81      32         1                  2                 2                 0
82      35         0                  2                 2                 0
83      34         1                  2                 4                 0
84      35         0                  2                 2                 0
85      34         1                  2                 2                 1
86      34         1                  2                 2                 0
87      33         1                  2                 2                 1
88      32         1                  2                 2                 1
89      34         1                  2                 2                 0
90      33         1                  2                 2                 1
91      40         0                  2                 3                 0
92      34         1                  2                 2                 1
93      33         0                  2                 2                 0
94      34         0                  2                 2                 0
95      32         0                  2                 2                 0
96      42         0                  2                 2                 1
97      34         0                  2                 1                 1
98      29         1                  2                 0                 0
99      24         1                  2                 1                 0
100     21         1                  2                 0                 1
101     21         1                  2                 0                 1
102     33         0                  2                 1                 0
103     33         0                  2                 2                 0
104     31         0                  2                 3                 0
105     33         1                  2                 2                 1
106     28         1                  2                 1                 1
107     33         1                  2                 2                 1
108     30         0                  2                 2                 1
109     32         1                  2                 2                 1
110     42         1                  1                 1                 0
111     34         0                  2                 3                 1
112     26         0                  2                 1                 1
113     31         1                  2                 1                 1
114     31         1                  2                 1                 1
115     31         1                  2                 2                 1
116     44         1                  2                 4                 0
117     30         0                  2                 2                 0
118     27         1                  2                 1                 0
119     34         0                  2                 2                 1
120     31         1                  1                 0                 1
121     41         1                  1                 0                 1
122     30         1                  2                 1                 0
123     35         1                  0                 0                 0
124     30         1                  2                 1                 0
125     38         1                  1                 0                 0
126     30         0                  2                 1                 1
127     28         1                  2                 1                 0
128     35         1                  2                 1                 0
129     29         0                  2                 2                 0
130     36         1                  2                 1                 0
131     36         1                  2                 1                 0
132     34         1                  2                 1                 1
133     47         1                  1                 1                 0
134     36         0                  2                 2                 0
135     26         0                  2                 1                 0
136     46         0                  2                 1                 0
137     33         1                  2                 2                 1
138     49         1                  2                 1                 1
139     55         1                  1                 2                 0
140     30         1                  2                 0                 0
141     32         1                  2                 1                 0
142     43         1                  1                 1                 0
143     23         0                  1                 1                 1
144     36         1                  2                 2                 0
145     36         1                  2                 2                 1
146     36         1                  2                 1                 0
147     30         1                  2                 1                 0
148     30         0                  2                 1                 1
149     43         1                  2                 2                 0
150     32         1                  2                 1                 1
151     32         1                  2                 1                 0
152     25         1                  2                 1                 0
153     34         1                  2                 2                 0
154     34         1                  2                 2                 0
155     37         1                  2                 1                 1
156     42         0                  2                 1                 0
157     24         0                  2                 1                 1
158     44         1                  2                 1                 1
159     26         1                  1                 1                 1
160     27         1                  2                 2                 0
161     28         1                  2                 2                 0
162     27         1                  2                 1                 1
163     41         1                  2                 1                 0
164     34         0                  1                 1                 0
165     26         0                  2                 1                 1
166     49         1                  1                 1                 0
167     36         0                  1                 1                 0
168     29         1                  1                 0                 1
169     40         1                  1                 1                 0
170     41         1                  2                 1                 0
171     46         0                  2                 2                 0
172     30         0                  2                 1                 0
173     30         1                  2                 1                 0
174     49         0                  1                 1                 0
175     42         1                  1                 1                 0
176     37         1                  1                 0                 0
177     28         1                  2                 1                 1
178     28         1                  2                 2                 1
179     41         1                  2                 1                 0
180     41         0                  2                 2                 0
181     33         0                  2                 1                 1
182     27         1                  1                 1                 0
183     29         0                  2                 0                 0
184     46         0                  2                 2                 0
185     27         1                  1                 1                 0
186     50         1                  1                 2                 1
187     29         0                  2                 1                 1
188     41         1                  2                 1                 0
189     50         1                  1                 1                 0
190     38         0                  1                 0                 0
191     30         1                  2                 0                 0
192     37         1                  2                 1                 0
193     31         1                  2                 1                 1
194     26         1                  2                 1                 1
195     29         1                  2                 0                 1
196     25         1                  2                 1                 0
197     22         0                  2                 0                 1
198     26         1                  2                 0                 1
199     25         1                  2                 0                 1
200     23         1                  2                 0                 1
201     21         1                  2                 0                 1
202     23         1                  2                 2                 1
203     26         0                  2                 0                 1
204     25         1                  2                 1                 1
205     22         0                  2                 1                 1
206     24         1                  2                 0                 1
207     25         1                  2                 1                 1
208     25         1                  2                 1                 1
209     24         1                  2                 1                 1
210     32         1                  2                 1                 1
211     25         0                  2                 1                 1
212     22         0                  2                 0                 1
213     26         1                  2                 1                 1
214     25         0                  2                 1                 1
215     25         1                  2                 1                 1
216     24         1                  2                 0                 0
217     27         1                  2                 0                 1
218     25         1                  2                 0                 0
219     23         1                  2                 1                 1
220     24         1                  2                 1                 1
221     25         1                  2                 1                 1
222     23         0                  2                 1                 1
223     25         1                  2                 1                 1
224     25         0                  2                 1                 1
225     47         1                  2                 2                 0
226     34         0                  2                 2                 1
227     37         0                  2                 2                 0
228     36         1                  2                 1                 0
229     68         1                  2                 0                 0
230     38         1                  2                 1                 0
231     39         1                  2                 1                 0
232     52         1                  2                 2                 0
233     38         1                  2                 0                 0
234     33         1                  2                 2                 0
235     43         1                  2                 1                 1
236     40         0                  2                 3                 0
237     32         0                  2                 1                 1
238     35         0                  2                 3                 1
239     25         1                  2                 1                 1
240     31         1                  2                 1                 1
241     38         1                  2                 2                 0
242     48         1                  2                 4                 0
243     33         1                  2                 1                 0
244     37         1                  2                 1                 0
245     56         0                  2                 4                 0
246     41         0                  2                 2                 1
247     35         1                  2                 3                 0
248     33         0                  2                 2                 0
249     33         0                  2                 2                 0
250     45         1                  2                 3                 0
251     38         1                  2                 2                 0
252     46         1                  2                 4                 0
253     47         1                  2                 3                 0
254     34         1                  2                 2                 0
255     35         1                  2                 2                 0
256     33         1                  2                 2                 1
257     38         1                  2                 3                 0
258     42         1                  2                 3                 1
259     52         1                  2                 4                 0
260     43         1                  2                 2                 0
261     38         1                  2                 3                 1

In [2]:
import warnings
import numpy as np

# Suppress overflow warning
warnings.filterwarnings("ignore", category=RuntimeWarning)
np.seterr(over='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [3]:
import numpy as np

# Apply the threshold to create the hesitant column
df['C.Non_hesitant'] = np.where(df['C.target_mean'] > 2.8, 1, 0)
# Display the resulting DataFrame with the aggregated target and hesitant column
print(df[['C.target_mean', 'C.Non_hesitant']])

     C.target_mean  C.Non_hesitant
0              4.0               1
1              2.4               0
2              4.0               1
3              3.0               1
4              2.1               0
5              2.4               0
6              3.9               1
7              4.0               1
8              2.1               0
9              4.0               1
10             3.6               1
11             3.0               1
12             3.0               1
13             2.8               0
14             2.9               1
15             2.6               0
16             2.1               0
17             3.2               1
18             3.2               1
19             2.1               0
20             2.9               1
21             4.0               1
22             1.9               0
23             2.9               1
24             1.9               0
25             2.1               0
26             3.0               1
27             3.8               1
28             3.0               1
29             1.2               0
30             3.2               1
31             3.0               1
32             1.8               0
33             4.0               1
34             3.0               1
35             3.6               1
36             3.0               1
37             3.9               1
38             3.0               1
39             3.8               1
40             4.0               1
41             3.0               1
42             2.8               0
43             4.0               1
44             1.4               0
45             2.1               0
46             3.8               1
47             3.3               1
48             3.6               1
49             4.0               1
50             2.1               0
51             2.0               0
52             3.0               1
53             0.0               0
54             2.9               1
55             3.9               1
56             2.2               0
57             0.0               0
58             2.8               0
59             2.2               0
60             2.9               1
61             3.9               1
62             2.8               0
63             3.9               1
64             2.8               0
65             3.7               1
66             2.7               0
67             2.8               0
68             3.2               1
69             4.0               1
70             3.0               1
71             4.0               1
72             2.3               0
73             2.6               0
74             4.0               1
75             3.8               1
76             2.6               0
77             3.0               1
78             2.8               0
79             4.0               1
80             3.4               1
81             3.7               1
82             3.0               1
83             2.8               0
84             4.0               1
85             2.8               0
86             3.8               1
87             3.0               1
88             3.0               1
89             3.0               1
90             4.0               1
91             3.0               1
92             3.0               1
93             3.8               1
94             3.4               1
95             3.7               1
96             3.8               1
97             3.3               1
98             2.8               0
99             4.0               1
100            3.9               1
101            3.0               1
102            3.0               1
103            2.9               1
104            1.8               0
105            4.0               1
106            2.9               1
107            4.0               1
108            3.4               1
109            2.7               0
110            1.9               0
111            3.8               1
112            4.0               1
113            3.0               1
114            2.9               1
115            2.7               0
116            3.1               1
117            3.0               1
118            2.1               0
119            2.7               0
120            2.1               0
121            1.8               0
122            0.0               0
123            4.0               1
124            2.9               1
125            3.0               1
126            2.6               0
127            2.6               0
128            3.0               1
129            4.0               1
130            2.1               0
131            0.4               0
132            3.0               1
133            1.3               0
134            3.0               1
135            2.2               0
136            3.0               1
137            3.0               1
138            3.1               1
139            2.4               0
140            2.9               1
141            2.8               0
142            1.8               0
143            3.0               1
144            2.8               0
145            3.0               1
146            1.9               0
147            2.2               0
148            1.6               0
149            2.4               0
150            2.6               0
151            1.6               0
152            2.0               0
153            2.1               0
154            2.8               0
155            3.1               1
156            2.8               0
157            4.0               1
158            4.0               1
159            2.2               0
160            4.0               1
161            3.3               1
162            2.9               1
163            4.0               1
164            2.1               0
165            2.1               0
166            2.1               0
167            2.6               0
168            4.0               1
169            2.2               0
170            2.1               0
171            2.2               0
172            1.8               0
173            1.7               0
174            3.0               1
175            2.1               0
176            2.1               0
177            3.1               1
178            2.9               1
179            2.1               0
180            2.8               0
181            3.8               1
182            2.2               0
183            2.1               0
184            2.9               1
185            3.8               1
186            2.1               0
187            2.2               0
188            4.0               1
189            1.7               0
190            2.2               0
191            2.8               0
192            2.9               1
193            2.8               0
194            2.8               0
195            2.7               0
196            3.2               1
197            2.0               0
198            3.9               1
199            3.8               1
200            2.9               1
201            3.0               1
202            4.0               1
203            2.7               0
204            4.0               1
205            3.0               1
206            2.9               1
207            3.7               1
208            2.1               0
209            2.1               0
210            2.4               0
211            2.9               1
212            4.0               1
213            3.0               1
214            2.7               0
215            2.9               1
216            3.0               1
217            3.0               1
218            2.1               0
219            2.7               0
220            2.1               0
221            2.1               0
222            3.2               1
223            2.9               1
224            3.0               1
225            3.0               1
226            3.0               1
227            1.6               0
228            2.1               0
229            3.0               1
230            3.3               1
231            3.9               1
232            2.0               0
233            2.1               0
234            1.8               0
235            2.1               0
236            4.0               1
237            3.7               1
238            3.0               1
239            4.0               1
240            2.8               0
241            3.0               1
242            3.6               1
243            1.7               0
244            2.1               0
245            3.8               1
246            3.0               1
247            3.9               1
248            4.0               1
249            2.8               0
250            2.1               0
251            3.4               1
252            4.0               1
253            4.0               1
254            2.9               1
255            3.0               1
256            4.0               1
257            4.0               1
258            2.0               0
259            2.8               0
260            2.9               1
261            4.0               1
262            2.9               1
263            2.3               0
264            4.0               1
265            3.0               1
266            2.1               0
267            3.6               1
268            4.0               1
269            3.9               1
270            4.0               1
271            3.2               1
272            0.0               0
273            4.0               1
274            4.0               1
275            4.0               1
276            3.0               1
277            2.8               0
278            3.6               1
279            2.6               0
280            2.1               0
281            1.9               0
282            4.0               1
283            3.0               1
284            3.3               1
285            3.3               1
286            3.2               1
287            3.9               1
288            2.6               0
289            2.1               0
290            1.7               0
291            3.8               1
292            3.0               1
293            2.7               0
294            3.3               1
295            1.2               0
296            3.0               1
297            2.1               0
298            4.0               1
299            3.9               1
300            3.6               1
301            2.7               0
302            3.0               1
303            4.0               1
304            2.6               0
305            2.3               0
306            2.8               0
307            3.0               1
308            3.9               1
309            3.0               1
310            4.0               1
311            3.0               1
312            3.6               1
313            4.0               1
314            3.8               1
315            3.8               1
316            2.6               0
317            2.6               0
318            3.7               1
319            2.1               0
320            2.1               0
321            3.9               1
322            3.0               1
323            1.8               0
324            3.6               1
325            3.0               1
326            4.0               1
327            1.4               0
328            3.6               1
329            2.9               1
330            4.0               1
331            2.8               0
332            3.3               1
333            3.9               1
334            2.9               1
335            3.0               1
336            1.4               0
337            2.7               0
338            4.0               1
339            2.3               0
340            2.2               0
341            2.1               0
342            0.0               0
343            2.8               0
344            0.1               0
345            3.7               1
346            0.7               0
347            3.4               1
348            1.3               0
349            2.7               0
350            2.7               0
351            3.0               1
352            3.0               1
353            3.4               1
354            2.4               0
355            3.9               1
356            2.9               1
357            3.0               1
358            3.3               1
359            2.3               0
360            3.0               1
361            2.6               0
362            1.9               0
363            3.0               1
364            3.9               1
365            2.1               0
366            4.0               1
367            3.1               1
368            2.1               0
369            2.9               1
370            2.9               1
371            2.1               0
372            3.9               1
373            2.8               0
374            3.1               1
375            2.1               0
376            3.1               1
377            3.0               1
378            4.0               1
379            3.2               1
380            2.8               0
381            3.0               1
382            3.2               1
383            2.3               0
384            4.0               1
385            4.0               1
386            1.4               0
387            3.4               1
388            3.0               1
389            4.0               1
390            4.0               1
391            2.0               0
392            3.2               1
393            2.8               0
394            4.0               1
395            4.0               1
396            2.9               1
397            4.0               1
398            2.9               1
399            4.0               1
400            4.0               1
401            2.7               0
402            3.4               1
403            2.6               0
404            4.0               1
405            3.6               1
406            3.0               1
407            3.9               1
408            4.0               1
409            3.4               1
410            3.6               1
411            2.7               0
412            4.0               1
413            4.0               1
414            3.3               1
415            0.7               0
416            3.4               1
417            2.7               0
418            2.4               0
419            4.0               1
420            2.9               1
421            3.0               1
422            2.1               0
423            1.6               0
424            4.0               1
425            3.1               1
426            3.0               1
427            2.9               1
428            4.0               1
429            2.6               0
430            3.6               1
431            4.0               1
432            2.1               0
433            2.8               0
434            2.9               1
435            2.1               0
436            3.3               1
437            4.0               1
438            0.0               0
439            3.7               1
440            3.0               1
441            0.3               0
442            3.9               1
443            2.9               1
444            3.9               1
445            2.0               0
446            3.1               1
447            2.2               0
448            1.6               0
449            3.6               1
450            3.9               1
451            3.0               1
452            3.8               1
453            2.6               0
454            2.8               0
455            3.1               1
456            3.3               1
457            3.9               1
458            2.7               0
459            3.2               1
460            4.0               1
461            2.3               0
462            3.0               1
463            2.6               0
464            3.0               1
465            2.1               0
466            3.6               1
467            3.0               1
468            3.0               1
469            2.7               0
470            4.0               1
471            2.9               1
472            3.0               1
473            2.7               0
474            3.0               1
475            2.6               0
476            2.7               0
477            3.8               1
478            2.7               0
479            3.0               1
480            3.0               1
481            3.0               1
482            4.0               1
483            2.9               1
484            1.9               0
485            0.0               0
486            2.1               0
487            2.8               0
488            3.0               1
489            2.3               0
490            3.0               1
491            0.0               0
492            0.3               0
493            3.7               1
494            2.3               0
495            3.0               1
496            2.1               0
497            2.8               0
498            3.2               1
499            2.1               0
500            2.2               0
501            2.3               0
502            1.6               0
503            1.6               0
504            1.7               0
505            1.6               0
506            2.1               0
507            1.0               0
508            3.0               1
509            2.1               0
510            2.8               0
511            2.6               0
512            1.8               0
513            2.9               1
514            2.1               0
515            2.9               1
516            1.9               0
517            2.3               0
518            3.0               1
519            2.1               0
520            3.0               1
521            3.0               1
522            3.0               1
523            3.0               1
524            2.4               0
525            2.8               0
526            2.1               0
527            2.4               0
528            3.6               1
529            2.4               0
530            2.9               1
531            3.0               1
532            2.4               0
533            2.1               0
534            2.4               0
535            3.4               1
536            2.1               0
537            2.8               0
538            3.0               1
539            2.1               0
540            2.8               0
541            2.0               0
542            3.1               1
543            2.1               0
544            2.1               0
545            2.7               0
546            3.0               1
547            2.8               0
548            3.0               1
549            2.1               0
550            3.0               1
551            3.0               1
552            3.7               1
553            4.0               1

In [4]:
df.drop(columns ='C.target_mean', inplace=True)
df.head()

,A.Age,A.Gender,A.Education Level,A.Monthly Income,A.Marital Status,A.Pregnancy Status,A.Breastfeeding Status,A.Direct Patient Contact,A.Job Type,A.Years of Employment,A.COVID-19 Patient Care,A.Existing Illnesses,A.COVID-19 History,A.Severe was your infection,A.Additional Vaccines,A.Immunity Boosters,B. Vaccination Status,B.Vaccine Choice,B.Vaccine Side Effects,B.Family/Friend Side Effects,B.View of vaccine,D.Vaccine Protection Perception,D.Side Effect Confidence,D.Clinical Trial Confidence,D.Chip Belief,D.Mandatory Belief,D.Halal Doubt,D.Alternative Medicine Belief,A.Service State_Johor,A.Service State_Kedah,A.Service State_Kelantan,A.Service State_Melaka,A.Service State_Neger Sembilan,A.Service State_Pahang,A.Service State_Perak,A.Service State_Perlis,A.Service State_Pulau Pinang,A.Service State_Sabah,A.Service State_Sarawak,A.Service State_Selangor,A.Service State_Terengganu,A.Service State_Wilayah Persekutuan Kuala Lumpur,A.Service State_Wilayah Persekutuan Putrajaya,A.Ethnicity_Cina,A.Ethnicity_India,A.Ethnicity_Indigenous,A.Ethnicity_Melayu,A.Ethnicity_Not citizen,A.Religion_Buddha,A.Religion_Hindu,A.Religion_Islam,A.Religion_Kristian,A.Religion_Others,A. Blog,A.Internet,A.KK,A. LamanMS,A. Orang,A.MediaMassa,A.COVID-19 Risk Perception,A.COVID-19 Concern Level,C.Non_hesitant
0,34,1,2,2,0,0,0,1,1,10,1,0,1,3,0,0,3,1,1,0,0,4,4,4,4,4,4,3,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,1,2,1
1,36,0,2,3,0,0,0,1,1,11,1,0,1,1,1,1,3,1,1,1,2,4,4,4,4,2,4,4,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,3,5,0
2,35,1,2,2,0,0,0,1,1,10,1,0,1,1,0,0,3,1,0,0,0,3,3,3,4,3,4,3,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,1,3,3,1
3,40,1,2,2,0,0,0,1,1,16,1,1,1,1,0,0,3,1,1,0,0,4,3,3,4,3,3,4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,1,3,3,1
4,32,1,2,1,0,0,0,1,1,10,0,0,0,0,1,0,3,1,1,1,2,2,2,2,4,2,3,2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,1,1,1,1,2,3,0

In [5]:
target=df["C.Non_hesitant"]
features=df.drop('C.Non_hesitant',axis=1)

In [6]:
# Split data into train and test sets

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split the dataset into training + development set and test set
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size = 0.2, random_state = 0)

# RANDOM FOREST

In [7]:
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# Random Forest Bagging
model_bagging_rf = BaggingClassifier(estimator=RandomForestClassifier(), n_estimators=10, random_state=7)

# Cross-validation
print("Model: Random Forest")
scores_rf = cross_val_score(model_bagging_rf, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold: ", scores_rf)
print("Mean Accuracy (Validation):", scores_rf.mean())
print("-" * 50)

# Test set evaluation
model_bagging_rf.fit(x_train, y_train)
test_predict_rf = model_bagging_rf.predict(x_test)
print("Random Forest Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_rf))
print("=" * 50)

Model: Random Forest
Accuracy scores for each fold:  [0.84269663 0.88764045 0.83146067 0.84090909 0.86363636]
Mean Accuracy (Validation): 0.8532686414708885
--------------------------------------------------
Random Forest Bagging - Accuracy (Test): 0.8558558558558559
==================================================

# BAGGING

NN

In [8]:
# Import necessary libraries
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# Neural Network with one hidden layer of 5 neurons
model_bagging_nn = BaggingClassifier(
    estimator=MLPClassifier(hidden_layer_sizes=(5,10), max_iter=200, random_state=7), 
    n_estimators=10, 
    random_state=7
)

# Cross-validation
print("Model: Neural Network (5 neurons in the hidden layer)")
scores_nn = cross_val_score(model_bagging_nn, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold: ", scores_nn)
print("Mean Accuracy (Validation):", scores_nn.mean())
print("-" * 50)

# Test set evaluation
model_bagging_nn.fit(x_train, y_train)
test_predict_nn = model_bagging_nn.predict(x_test)
print("Neural Network Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_nn))
print("=" * 50)

Model: Neural Network (5 neurons in the hidden layer)

/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Accuracy scores for each fold:  [0.86516854 0.79775281 0.79775281 0.72727273 0.79545455]
Mean Accuracy (Validation): 0.7966802860061286
--------------------------------------------------

/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Neural Network Bagging - Accuracy (Test): 0.8468468468468469
==================================================

/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [9]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# Linear SVM Bagging (with probability=True for flexibility)
model_bagging_linear_svm = BaggingClassifier(
    estimator=SVC(kernel='linear', C=0.1, probability=True),
    n_estimators=10,
    random_state=7
)

# Cross-validation
print("Model: Linear SVM (C=0.1)")
scores_linear_svm = cross_val_score(model_bagging_linear_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold:", scores_linear_svm)
print("Mean Accuracy (Validation):", scores_linear_svm.mean())
print("-" * 50)

# Test set evaluation
model_bagging_linear_svm.fit(x_train, y_train)
test_predict_linear_svm = model_bagging_linear_svm.predict(x_test)
print("Linear SVM Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_linear_svm))
print("=" * 50)

Model: Linear SVM (C=0.1)
Accuracy scores for each fold: [0.83146067 0.83146067 0.85393258 0.85227273 0.86363636]
Mean Accuracy (Validation): 0.8465526046986721
--------------------------------------------------
Linear SVM Bagging - Accuracy (Test): 0.8738738738738738
==================================================

In [10]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# Polynomial SVM Bagging (with probability=True for flexibility)
model_bagging_poly_svm = BaggingClassifier(
    estimator=SVC(kernel='poly', C=1, degree=3, gamma='scale', probability=True),
    n_estimators=10,
    random_state=7
)

# Cross-validation
print("Model: Polynomial SVM (C=1, degree=3)")
scores_poly_svm = cross_val_score(model_bagging_poly_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold:", scores_poly_svm)
print("Mean Accuracy (Validation):", scores_poly_svm.mean())
print("-" * 50)

# Fit and Test evaluation
model_bagging_poly_svm.fit(x_train, y_train)
test_predict_poly_svm = model_bagging_poly_svm.predict(x_test)
print("Polynomial SVM Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_poly_svm))
print("=" * 50)

Model: Polynomial SVM (C=1, degree=3)
Accuracy scores for each fold: [0.75280899 0.83146067 0.7752809  0.80681818 0.80681818]
Mean Accuracy (Validation): 0.7946373850868232
--------------------------------------------------
Polynomial SVM Bagging - Accuracy (Test): 0.8468468468468469
==================================================

In [11]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# RBF SVM Bagging (with probability=True for flexibility)
model_bagging_rbf_svm = BaggingClassifier(
    estimator=SVC(kernel='rbf', C=10, gamma='scale', probability=True),
    n_estimators=10,
    random_state=7
)

# Cross-validation
print("Model: RBF SVM (C=10, gamma='scale')")
scores_rbf_svm = cross_val_score(model_bagging_rbf_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold:", scores_rbf_svm)
print("Mean Accuracy (Validation):", scores_rbf_svm.mean())
print("-" * 50)

# Test set evaluation
model_bagging_rbf_svm.fit(x_train, y_train)
test_predict_rbf_svm = model_bagging_rbf_svm.predict(x_test)
print("RBF SVM Bagging - Accuracy (Test):", metrics.accuracy_score(y_test, test_predict_rbf_svm))
print("=" * 50)

Model: RBF SVM (C=10, gamma='scale')
Accuracy scores for each fold: [0.83146067 0.85393258 0.80898876 0.82954545 0.875     ]
Mean Accuracy (Validation): 0.8397854954034731
--------------------------------------------------
RBF SVM Bagging - Accuracy (Test): 0.8738738738738738
==================================================

# Boosting

In [12]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

# Define the Gradient Boosting classifier
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Cross-validation
cv_scores = cross_val_score(gbc, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold (CV): ", cv_scores)
print("Mean Accuracy (Validation): {:.4f}".format(cv_scores.mean()))
print("-" * 50)

# Fit the model on the full training data
gbc.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred = gbc.predict(x_test)
accuracy = accuracy_score(y_test, y_test_pred)

# Print evaluation metrics
print(f'Accuracy (Test): {accuracy:.4f}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred))
print('Classification Report:')
print(classification_report(y_test, y_test_pred))
print("=" * 50)

Accuracy scores for each fold (CV):  [0.79775281 0.86516854 0.83146067 0.78409091 0.85227273]
Mean Accuracy (Validation): 0.8261
--------------------------------------------------
Accuracy (Test): 0.8739
Confusion Matrix:
[[37  8]
 [ 6 60]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.82      0.84        45
           1       0.88      0.91      0.90        66

    accuracy                           0.87       111
   macro avg       0.87      0.87      0.87       111
weighted avg       0.87      0.87      0.87       111

==================================================

In [13]:
import xgboost as xgb
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np

# Define the XGBoost classifier
xgb_clf = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Cross-validation
cv_scores = cross_val_score(xgb_clf, x_train, y_train, cv=5, scoring='accuracy')
print("Accuracy scores for each fold (CV): ", cv_scores)
print("Mean Accuracy (Validation): {:.4f}".format(cv_scores.mean()))
print("-" * 50)

# Fit the model on the full training data
xgb_clf.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred = xgb_clf.predict(x_test)
accuracy = accuracy_score(y_test, y_test_pred)

# Print evaluation metrics
print(f'Accuracy (Test): {accuracy:.4f}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred))
print('Classification Report:')
print(classification_report(y_test, y_test_pred))
print("=" * 50)

Accuracy scores for each fold (CV):  [0.83146067 0.85393258 0.83146067 0.82954545 0.88636364]
Mean Accuracy (Validation): 0.8466
--------------------------------------------------
Accuracy (Test): 0.8739
Confusion Matrix:
[[37  8]
 [ 6 60]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.82      0.84        45
           1       0.88      0.91      0.90        66

    accuracy                           0.87       111
   macro avg       0.87      0.87      0.87       111
weighted avg       0.87      0.87      0.87       111

==================================================

# ADABOOSTING

rbf

In [14]:
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define the RBF SVM base estimator with updated parameters
rbf_svm = SVC(kernel='rbf', probability=True, C=10, gamma='scale', random_state=7)

# AdaBoost with RBF SVM
ada_rbf_svm = AdaBoostClassifier(estimator=rbf_svm, n_estimators=10, random_state=7)

# Cross-validation
cv_scores_rbf_svm = cross_val_score(ada_rbf_svm, x_train, y_train, cv=5, scoring='accuracy')
print("RBF SVM - Accuracy scores for each fold (CV): ", cv_scores_rbf_svm)
print("RBF SVM - Mean Accuracy (Validation): {:.4f}".format(cv_scores_rbf_svm.mean()))
print("-" * 50)

# Fit the model on the full training data
ada_rbf_svm.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred_rbf_svm = ada_rbf_svm.predict(x_test)
accuracy_rbf_svm = accuracy_score(y_test, y_test_pred_rbf_svm)

# Print evaluation metrics
print(f'RBF SVM - Accuracy (Test): {accuracy_rbf_svm:.4f}')
print('RBF SVM - Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred_rbf_svm))
print('RBF SVM - Classification Report:')
print(classification_report(y_test, y_test_pred_rbf_svm))
print("=" * 50)

RBF SVM - Accuracy scores for each fold (CV):  [0.57303371 0.57303371 0.57303371 0.57954545 0.57954545]
RBF SVM - Mean Accuracy (Validation): 0.5756
--------------------------------------------------
RBF SVM - Accuracy (Test): 0.5946
RBF SVM - Confusion Matrix:
[[ 0 45]
 [ 0 66]]
RBF SVM - Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        45
           1       0.59      1.00      0.75        66

    accuracy                           0.59       111
   macro avg       0.30      0.50      0.37       111
weighted avg       0.35      0.59      0.44       111

==================================================

/Applications/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [15]:
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define the Linear SVM base estimator with updated parameters
linear_svm = SVC(kernel='linear', probability=True, C=0.1, random_state=7)

# AdaBoost with Linear SVM
ada_linear_svm = AdaBoostClassifier(estimator=linear_svm, n_estimators=10, random_state=7)

# Cross-validation
cv_scores_linear_svm = cross_val_score(ada_linear_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Linear SVM - Accuracy scores for each fold (CV): ", cv_scores_linear_svm)
print("Linear SVM - Mean Accuracy (Validation): {:.4f}".format(cv_scores_linear_svm.mean()))
print("-" * 50)

# Fit the model on the full training data
ada_linear_svm.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred_linear_svm = ada_linear_svm.predict(x_test)
accuracy_linear_svm = accuracy_score(y_test, y_test_pred_linear_svm)

# Print evaluation metrics
print(f'Linear SVM - Accuracy (Test): {accuracy_linear_svm:.4f}')
print('Linear SVM - Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred_linear_svm))
print('Linear SVM - Classification Report:')
print(classification_report(y_test, y_test_pred_linear_svm))
print("=" * 50)

Linear SVM - Accuracy scores for each fold (CV):  [0.73033708 0.73033708 0.68539326 0.64772727 0.76136364]
Linear SVM - Mean Accuracy (Validation): 0.7110
--------------------------------------------------
Linear SVM - Accuracy (Test): 0.7477
Linear SVM - Confusion Matrix:
[[18 27]
 [ 1 65]]
Linear SVM - Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.40      0.56        45
           1       0.71      0.98      0.82        66

    accuracy                           0.75       111
   macro avg       0.83      0.69      0.69       111
weighted avg       0.80      0.75      0.72       111

==================================================

In [16]:
import numpy as np
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Define the Polynomial SVM base estimator
poly_svm = SVC(kernel='poly', C=1, degree=3, gamma='scale', probability=True, random_state=7)

# AdaBoost with Polynomial SVM
ada_poly_svm = AdaBoostClassifier(estimator=poly_svm, n_estimators=10, random_state=7)

# Cross-validation
cv_scores_poly_svm = cross_val_score(ada_poly_svm, x_train, y_train, cv=5, scoring='accuracy')
print("Polynomial SVM - Accuracy scores for each fold (CV): ", cv_scores_poly_svm)
print("Polynomial SVM - Mean Accuracy (Validation): {:.4f}".format(cv_scores_poly_svm.mean()))
print("-" * 50)

# Fit the model on the full training data
ada_poly_svm.fit(x_train, y_train)

# Evaluate the model on the test data
y_test_pred_poly_svm = ada_poly_svm.predict(x_test)
accuracy_poly_svm = accuracy_score(y_test, y_test_pred_poly_svm)

# Print evaluation metrics
print(f'Polynomial SVM - Accuracy (Test): {accuracy_poly_svm:.4f}')
print('Polynomial SVM - Confusion Matrix:')
print(confusion_matrix(y_test, y_test_pred_poly_svm))
print('Polynomial SVM - Classification Report:')
print(classification_report(y_test, y_test_pred_poly_svm))
print("=" * 50)

Polynomial SVM - Accuracy scores for each fold (CV):  [0.57303371 0.57303371 0.57303371 0.57954545 0.57954545]
Polynomial SVM - Mean Accuracy (Validation): 0.5756
--------------------------------------------------
Polynomial SVM - Accuracy (Test): 0.5946
Polynomial SVM - Confusion Matrix:
[[ 0 45]
 [ 0 66]]
Polynomial SVM - Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        45
           1       0.59      1.00      0.75        66

    accuracy                           0.59       111
   macro avg       0.30      0.50      0.37       111
weighted avg       0.35      0.59      0.44       111

==================================================

/Applications/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Applications/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [17]:
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score
from sklearn import metrics

# KNN (k=23) - Bagging only
model_bagging_knn = BaggingClassifier(
    estimator=KNeighborsClassifier(n_neighbors=9),
    n_estimators=10,
    random_state=7
)
print("Model: KNN (k=23) - Bagging")
scores = cross_val_score(model_bagging_knn, x_train, y_train, cv=5, scoring='accuracy')
print("Validation Accuracy:", scores.mean())
model_bagging_knn.fit(x_train, y_train)
print("Test Accuracy:", metrics.accuracy_score(y_test, model_bagging_knn.predict(x_test)))
print("=" * 50)

# Decision Tree (depth=4) - Bagging
model_bagging_dt = BaggingClassifier(
    estimator=DecisionTreeClassifier(max_depth=3, random_state=7),
    n_estimators=10,
    random_state=7
)
print("Model: Decision Tree (depth=4) - Bagging")
scores = cross_val_score(model_bagging_dt, x_train, y_train, cv=5, scoring='accuracy')
print("Validation Accuracy:", scores.mean())
model_bagging_dt.fit(x_train, y_train)
print("Test Accuracy:", metrics.accuracy_score(y_test, model_bagging_dt.predict(x_test)))
print("=" * 50)

# Decision Tree (depth=4) - AdaBoost
model_adaboost_dt = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=3, random_state=7),
    n_estimators=50,
    random_state=7
)
print("Model: Decision Tree (depth=3) - AdaBoost")
scores = cross_val_score(model_adaboost_dt, x_train, y_train, cv=5, scoring='accuracy')
print("Validation Accuracy:", scores.mean())
model_adaboost_dt.fit(x_train, y_train)
print("Test Accuracy:", metrics.accuracy_score(y_test, model_adaboost_dt.predict(x_test)))
print("=" * 50)

# MultinomialNB - Bagging only
model_bagging_mnb = BaggingClassifier(
    estimator=MultinomialNB(),
    n_estimators=10,
    random_state=7
)
print("Model: MultinomialNB - Bagging")
scores = cross_val_score(model_bagging_mnb, x_train, y_train, cv=5, scoring='accuracy')
print("Validation Accuracy:", scores.mean())
model_bagging_mnb.fit(x_train, y_train)
print("Test Accuracy:", metrics.accuracy_score(y_test, model_bagging_mnb.predict(x_test)))
print("=" * 50)

Model: KNN (k=23) - Bagging
Validation Accuracy: 0.7765832482124617
Test Accuracy: 0.8288288288288288
==================================================
Model: Decision Tree (depth=4) - Bagging
Validation Accuracy: 0.8374872318692544
Test Accuracy: 0.8558558558558559
==================================================
Model: Decision Tree (depth=3) - AdaBoost
Validation Accuracy: 0.8329417773237997
Test Accuracy: 0.8468468468468469
==================================================
Model: MultinomialNB - Bagging
Validation Accuracy: 0.7650663942798774
Test Accuracy: 0.8378378378378378
==================================================